name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  tag:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - run: npm install -g corepack
      - run: corepack enable
      - run: pnpm i
      - run: pnpm build

      - name: Commit dist and update tags
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          ORIGINAL_TAG=${{ github.ref_name }}
          MAJOR_TAG=$(echo "$ORIGINAL_TAG" | cut -d. -f1)

          git add -f dist/
          git commit -m "chore: build dist files for $ORIGINAL_TAG" || echo "No changes to commit"
          git push origin HEAD:${{ github.event.base_ref || 'main' }}

          git tag -f "$ORIGINAL_TAG"
          git tag -f "$MAJOR_TAG"

          git push origin "$ORIGINAL_TAG" --force
          git push origin "$MAJOR_TAG" --force
