name: release

on:
  pull_request:
    paths:
      - .github/workflows/release.yaml
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  tag:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - run: npm install -g corepack
      - run: corepack enable
      - run: pnpm i
      - run: pnpm build
      - name: Update v1 tag
        if: github.event_name != 'pull_request'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/
          git commit -m "chore: generate dist files" || echo "No changes to commit"
          git tag -f v1
          git push origin HEAD
          git push origin v1 --force
